# Generated by Django 5.0.4 on 2024-12-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_file',
            new_name='upload_video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='download_video_file',
            field=models.FileField(blank=True, null=True, upload_to='processed_videos/'),
        ),
    ]
